Pcf 92
eastgenomics/eggd_staraligner pull request #3
Opened 2023-04-05 11:38 UTC by corbin-chris

Please see these example runs, which addressed a previous memory issue:
https://platform.dnanexus.com/projects/GFfV0qQ42QQVf6VX12zxxvx3/monitor/job/GQfYqPj42QQpYXz8qkPK99V5
https://platform.dnanexus.com/projects/GFfV0qQ42QQVf6VX12zxxvx3/monitor/job/GQfYqGQ42QQbvxQG12bf4jBQ

Other changes relatively minor - changing a parameter's name to match eggd_starfusion and eggd_fusioninspector, adding sample names to log files, and removing some redundant release info.

2023-04-05 13:41 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`src/script.sh` line 196 at r1](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3#-NSGd2zi5VKQlIkmmprx:-NSGd2zi5VKQlIkmmpry:b-vgprd6) ([raw file](https://github.com/eastgenomics/eggd_staraligner/blob/7a9dd61063bfd600ec2516752abeb765c849c4ef/src/script.sh#L196)):*
> ```Shell
> # This generates a .mark_duplicates.star.Processed.out.bam file with the duplicates marked
> # Generate a .bai index file for the duplicate-marked bam
> sentieon STAR --runMode inputAlignmentsFromBAM --inputBAMfile ${SORTED_BAM} --bamRemoveDuplicatesType UniqueIdentical --outFileNamePrefix /home/dnanexus/out/${sample_name}.mark_duplicates.star. --limitBAMsortRAM 50000000000
> ```

How did you select this value? The jobs you linked used an instance type of mem3_ssd1_v2_x32 which is different from the one mentioned in the json which is mem1_ssd1_x32. Will this value effect if the job is run on the smaller instance at mem1_ssd1_x32


<!-- Sent from Reviewable.io -->

2023-04-06 10:31 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/script.sh` line 196 at r1](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3#-NSGd2zi5VKQlIkmmprx:-NSL5rv_5KmgfbhhMR-o:bs7m6gf) ([raw file](https://github.com/eastgenomics/eggd_staraligner/blob/7a9dd61063bfd600ec2516752abeb765c849c4ef/src/script.sh#L196)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

How did you select this value? The jobs you linked used an instance type of mem3_ssd1_v2_x32 which is different from the one mentioned in the json which is mem1_ssd1_x32. Will this value effect if the job is run on the smaller instance at mem1_ssd1_x32
</blockquote></details>

Good point. The min requested by the error was 32 GB, and mem1_ssd1_x32 has 60 GB, so I picked 50 GB to give the command plenty of space while leaving 10 GB for other processes. I ran a job on mem1_ssd1_x32 and it was successful so it looks like mem1_ssd1_x32 is fine: https://platform.dnanexus.com/projects/GFfV0qQ42QQVf6VX12zxxvx3/monitor/job/GQg8Qb842QQZf79KGx9gk3fV


<!-- Sent from Reviewable.io -->

2023-04-06 11:00 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`dxapp.json` line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3#-NSLDIKO6YvsYCeXBtLL:-NSLDIKPBgcDk6lmMjaV:bd9dwkf) ([raw file](https://github.com/eastgenomics/eggd_staraligner/blob/7a9dd61063bfd600ec2516752abeb765c849c4ef/dxapp.json#L116)):*
> ```JSON
>       "timeoutPolicy": {
>         "*": {
>           "hours": 1
> ```

can you increase this 2hours? The standard time looks to be around ~48 mins which is close to the timeout


<!-- Sent from Reviewable.io -->

2023-04-06 11:08 UTC, corbin-chris reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`dxapp.json` line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3#-NSLDIKO6YvsYCeXBtLL:-NSLF6a01E-WiQatlbMo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_staraligner/blob/7a9dd61063bfd600ec2516752abeb765c849c4ef/dxapp.json#L116)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can you increase this 2hours? The standard time looks to be around ~48 mins which is close to the timeout
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 11:08 UTC, Aisha-D approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_staraligner/3#-:-NSLFFfd2aJ-_x5INDGt:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-06 11:08 UTC, merged